AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - Gemfile
    - Rakefile
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  Enabled: false

Naming/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
